plugins = []
headers = []
redirects = []

[functions]

[functions."*"]

[build]
publish = "/Users/zhengjingzhong/Desktop/氧阁/产品需求管理/产品需求原型项目/ai-go/dist"
publishOrigin = "ui"
commandOrigin = "ui"
command = "npm run build"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]